export const MEMORY_TTL_DAYS = {
  SOMA_NAV_DATA: 7,
  SOMA_FUND_COMPOSITION: 30,
  SOMA_FUND_RESEARCH: 30,
  KIRAN_MACRO_BULLETIN: 7,
  KIRAN_CLIENT_RISK_PROFILE: 90,
  KIRAN_HEDGE_MAP: 90,
  VIKRAM_CLIENT_GOAL_ASSESSMENT: 90,
  VIKRAM_GOAL_HYPOTHESIS: 7,
  VIKRAM_STRATEGY_FRAMEWORK: 365,
  VIKRAM_MARKET_CYCLE_ANALYSIS: 90,
  ARIA_CRITIQUE_REPORT: 365,
  ARIA_PREFLIGHT_REPORT: 7,
  PRIYA_PORTFOLIO_DRAFT: 90,
  DHRUV_COMMITTEE_VOTE: Infinity,
  DHRUV_FINAL_PORTFOLIO: Infinity,
  RIYA_BEHAVIORAL_FINGERPRINT: 30,
} as const

export type MemoryType = keyof typeof MEMORY_TTL_DAYS
