import { randomUUID } from 'crypto'
import { getGpt4o } from '@/lib/azure-openai'
import {
  FinalPortfolioPacket,
  FinalPortfolioPacketSchema,
  ClientGoalAssessment,
  PortfolioDraft,
} from '@/lib/agents/types'
import logger from '@/lib/logger'
import { DHRUV_SYSTEM_PROMPT_V1 } from '@/lib/agents/prompts'
import { REQUIRED_DISCLAIMER } from '@/lib/agents/sebi'

const DATA_FRESHNESS_DAYS = 7
const BACKTEST_DISCLAIMER =
  'Backtest results are hypothetical, based on historical data, and do not guarantee future performance. They are shown for educational discussion only.'
const CONFLICT_DISCLOSURE =
  'This platform does not receive commissions from fund houses. Allocations are generated by an educational simulation and are not biased by commercial relationships.'
const VALIDITY_DISCLOSURE =
  'This packet is valid for 30 days from generation. Market conditions, fund data, and personal circumstances may change, requiring a fresh review.'

export class PacketCompiler {
  async compileFinalPortfolioPacket(
    draft: PortfolioDraft,
    pipelineRunId: string,
    goalAssessment: ClientGoalAssessment,
    sebiReport?: any,
  ): Promise<FinalPortfolioPacket> {
    logger.info({ pipelineRunId, draftId: draft.portfolio_id }, 'DHRUV: compileFinalPortfolioPacket invoked')

    const gpt = getGpt4o()
    const prompt = `
Generate a concise executive summary (max 500 words) for the following hypothetical portfolio draft.
Frame it as an educational discussion, not investment advice.

Client Goal Summary:
${JSON.stringify(goalAssessment, null, 2)}

Portfolio Draft:
${JSON.stringify(draft, null, 2)}

Instructions:
1. Summarize the goal, strategy, and hypothetical allocation.
2. Mention the confidence score and key risks.
3. Include the phrase "hypothetical portfolio for educational discussion".
4. Do not tell the client to buy, sell, or invest.
`

    let executiveSummary = 'Hypothetical portfolio packet compiled for educational discussion.'
    try {
      const response = await gpt.chat.completions.create({
        model: 'gpt-4o',
        messages: [
          { role: 'system', content: DHRUV_SYSTEM_PROMPT_V1 },
          { role: 'user', content: prompt },
        ],
        temperature: 0.3,
        max_tokens: 900,
      })
      executiveSummary = response.choices[0]?.message?.content?.trim() || executiveSummary
    } catch (err) {
      logger.warn({ err, pipelineRunId }, 'DHRUV: executive summary generation failed; using fallback')
    }

    const now = new Date()
    const validUntil = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000)

    const freshestAgeDays = this.computeFreshestAgeDays(draft)
    const dataFreshnessDisclosure = `Fund profile and snapshot data used in this packet is at most ${freshestAgeDays} days old. Data older than ${DATA_FRESHNESS_DAYS} days is flagged as stale for discussion.`

    const openObservations = (draft.open_critique_items || []).filter((f) => f.severity === 'MINOR' || f.severity === 'OBSERVATION')

    const packet: FinalPortfolioPacket = {
      packet_id: randomUUID(),
      pipeline_run_id: pipelineRunId,
      client_id: draft.client_id,
      generated_at: now.toISOString(),
      valid_until: validUntil.toISOString(),
      executive_summary: executiveSummary,
      client_goal_summary: goalAssessment,
      achievability_verdict: goalAssessment.achievability_verdict,
      full_portfolio: draft,
      risk_and_hedge_map: draft.hedge_instruments,
      backtest_summary: draft.backtest_summary,
      confidence_score_breakdown: draft.confidence_score,
      open_observations: openObservations,
      sebi_disclaimer: sebiReport?.disclaimer || REQUIRED_DISCLAIMER,
      data_freshness_disclosure: dataFreshnessDisclosure,
      backtest_disclaimer: BACKTEST_DISCLAIMER,
      conflict_of_interest_disclosure: CONFLICT_DISCLOSURE,
      validity_disclosure: VALIDITY_DISCLOSURE,
      audit_trail_pipeline_run_id: pipelineRunId,
    }

    return FinalPortfolioPacketSchema.parse(packet)
  }

  private computeFreshestAgeDays(draft: PortfolioDraft): number {
    const timestamps: number[] = []
    for (const fa of draft.fund_allocations) {
      if (fa.fund_profile_retrieved_at) {
        timestamps.push(new Date(fa.fund_profile_retrieved_at).getTime())
      }
    }
    if (timestamps.length === 0) return 0
    const oldest = Math.min(...timestamps)
    return Math.floor((Date.now() - oldest) / (1000 * 60 * 60 * 24))
  }
}
